addSbtPlugin("org.scala-js"       % "sbt-scalajs"      % "1.22.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native" % "0.5.12")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"     % "2.6.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"     % "0.14.7")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"       % "5.1.1")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"          % "2.3.1")
addSbtPlugin("rocks.earlyeffect"  % "sbt-marklit"      % "0.1.0")
