addSbtPlugin("com.eed3si9n"     % "sbt-projectmatrix" % "0.10.1")
addSbtPlugin("org.scala-js"     % "sbt-scalajs"       % "1.18.2")
addSbtPlugin("org.scala-native" % "sbt-scala-native"  % "0.5.7")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"      % "2.5.4")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"      % "0.14.2")
addSbtPlugin("com.github.sbt"   % "sbt-dynver"        % "5.1.0")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"           % "2.3.1")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"      % "3.12.2")
