on:
  pull_request:


permissions:
  contents: read

jobs:
  test:
    name: "Run All Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up a JDK for SBT
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: ./ci_auth.sh && sbt +test
